name: CMIKits
version: '${pom.version}'
main: me.seetch.cmikits.CMIKits
api-version: '1.20'
authors:
  - seetch
depend:
  - CMI
commands:
  kits:
    description: View all CMI starter kits
    usage: /kits [kit]
    permission: kits.use
permissions:
  kits.use:
    description: Allows using the command for yourself
    default: true