name: CMIKits
version: '${pom.version}'
main: me.seetch.cmikits.CMIKits
api-version: '1.21'
authors:
  - seetch
depend:
  - CMI
commands:
  kits:
    description: Просмотреть все стартовый наборы CMI
    usage: /kits [kit]
    permission: kits.use
permissions:
  kits.use:
    description: Позволяет использовать команду для себя
    default: true